### ISSUE TITLE
不要なファイルが存在している

### ISSUE THREAD

**Issue by LeavaTail** [pg-hobby/netttrs#1]
## チャットアプリ
easychat配下に`client`や`server`といった実行ファイルがあります。
以下の点で不適切だと思うので削除したほうが良いと思います。
  * 実行環境によって動作しない
  * `make`で生成することができる

`.gitignore`で対象から外したり、コミット前にフックして実行ファイルを削除してはどうですか？

**Comment by pg-hobby** [comment]
問題ないので却下します

**Comment by pg-hobby** [comment]
再検討します。
