### ISSUE TITLE
コンパイラ依存の書き方

### ISSUE THREAD

**Issue by LeavaTail** [pg-hobby/netttrs#2]
## Ｃプログラムの書き方について
`main()`や`return`を書かない書き方はコンパイラによってはエラーになるので、
特別な意図がなければ正しく記述したほうが良いと思います。

### 対象
上記の書き方を確認したソースは下記に示します。
  * `easychat/client.c`
  * `easychat/server.c`

**Comment by pg-hobby** [comment]
問題ありませんので却下します
